name: Java CI

on: [push]

jobs:
  build:
    name: Build jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run unit tests
        run: ./gradlew clean test

      - name: Run pitest
        run: ./gradlew clean pitest

      - name: Build jar
        run: ./gradlew clean build -x test